config/routes.rb
ChatTest::Engine.routes.draw do
  devise_for :users, class_name: 'ChatTest::User', module: :devise

  root to: 'conversations#index'
  resources :messages
  resources :conversations do
    resources :messages
  end
end

app/models/chat_test/application_record.rb
module ChatTest
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/chat_test/chat.rb
module ChatTest
  class Chat < ApplicationRecord
  end
end

app/models/chat_test/conversation.rb
module ChatTest
  class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
    has_many :messages, dependent: :destroy

    scope :between, -> (sender_id, recipient_id) do
      where("(conversations.sender_id = ? AND
        conversations.recipient_id =?) OR (conversations.sender_id = ? AND
        conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id
      )
    end
  end
end

app/models/chat_test/message.rb
module ChatTest
  class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :user

    validates_presence_of :body, :conversation_id, :user_id
  end
end

app/models/chat_test/user.rb
module ChatTest
  class User < ApplicationRecord
    has_many :members
    has_many :conversations, through: :members

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
  end
end

app/controllers/chat_test/application_controller.rb
module ChatTest
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/chat_test/chats_controller.rb
# require_dependency "chat_test/application_controller"

# module ChatTest
#   class ChatsController < ApplicationController
#     before_action :set_chat, only: [:show, :edit, :update, :destroy]

#     def index
#       @chats = Chat.all
#     end

#     def show
#     end

#     def new
#       @chat = Chat.new
#       @chats = Chat.all
#     end

#     def edit
#     end

#     def create
#       @chat = Chat.new(chat_params)

#       respond_to do |format|
#         if @chat.save
#           ActionCable.server.broadcast 'room_channel', content: @chat
#           format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
#           format.json { render :show, status: :created, location: @chat }
#           format.js
#         else
#           format.html { render :new }
#           format.json { render json: @chat.errors, status: :unprocessable_entity }
#         end
#       end
#     end

#     def update
#       respond_to do |format|
#         if @chat.update(chat_params)
#           format.html { redirect_to @chat, notice: 'Chat was successfully updated.'}
#           format.json { render :show, status: :ok, location: @chat }
#         else
#           format.html { render :edit }
#           format.json { render json: @chat.errors, status: :unprocessable_entity }
#         end
#       end
#     end

#     def destroy
#       @chat.destroy
#       ActionCable.server.broadcast 'remove_channel', content: @chat 

#       respond_to do |format|
#         format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
#         format.json { head :no_content }
#         format.js
#       end
#     end

#     private
    
#     def set_chat
#       @chat = Chat.find(params[:id])
#     end

#     def chat_params
#       params.require(:chat).permit(:message)
#     end
#   end
# end

app/controllers/chat_test/conversations_controller.rb
require_dependency "chat_test/application_controller"

module ChatTest
  class ConversationsController < ApplicationController
    before_action :authenticate_user!

    def index
      @users = User.all
      @conversations = Conversation.all
    end

    def create
      if Conversation.between(params[:sender_id], params[:recipient_id]).present? 
        @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
      else
        @conversation = Conversation.create!(conversation_params)
      end
      redirect_to conversation_messages_path(@conversation)
    end

    private

    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end
  end
end

app/controllers/chat_test/messages_controller.rb
require_dependency "chat_test/application_controller"

module ChatTest
  class MessagesController < ApplicationController
    # before_action :set_conversation

    before_action do
      @conversation = Conversation.find(params[:conversation_id])
    end

    def index
      @messages = @conversation.messages
      @message = @conversation.messages.new
    end

    def new
      @message = @conversation.messages.new
    end

    def create
      @message = @conversation.messages.new(message_params)

      if @message.save
        redirect_to conversation_messages_path(@conversation)
      end
    end

    private

    def set_conversation
      @conversation = ChatTest::Conversation.find(params[:conversation_id])
    end

    def message_params
      params.require(:message).permit(:body, :user_id)
    end
  end
end

app/helpers/chat_test/application_helper.rb
module ChatTest
  module ApplicationHelper
  end
end

app/helpers/chat_test/chats_helper.rb
module ChatTest
  module ChatsHelper
  end
end

app/helpers/chat_test/conversations_helper.rb
module ChatTest
  module ConversationsHelper
  end
end

app/helpers/chat_test/messages_helper.rb
module ChatTest
  module MessagesHelper
  end
end

app/views/chat_test/conversations/index.html.erb
<h1>My Inbox</h1>
<h1>All Conversations:</h1>
<% @conversations.each do |conversation| %>
  <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
    <% if conversation.sender_id == current_user.id %>
      <% recipient = ChatTest::User.find(conversation.recipient_id) %>
    <% else %>
      <% recipient = ChatTest::User.find(conversation.sender_id) %>
    <% end %>

    <h3><%= link_to recipient.email, conversation_messages_path(conversation)%></h3>
  <% end %>
<% end %>
<h1>All Users:</h1>
<% @users.each do |user| %>
  <% if user.id != current_user.id %><h3>
    <%= link_to user.email, conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post"%></h3>
  <% end %>
<% end %>

app/views/chat_test/messages/index.html.erb
<% @messages.each do |message| %>

  <% if message.body %>
    <% user = ChatTest::User.find(message.user_id) %>
    <%= user.email %><%= message.message_time %>
    <%= message.body %>
  <% end %>
<% end %>

<%= form_for [@message] do |f| %>
  <%= f.text_area :body %>
  <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
  <%= f.submit "Send Reply" %>
<% end %>

app/views/layouts/chat_test/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat test</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "chat_test/application", media: "all" %>
  <%= javascript_include_tag "chat_test/application" %>
</head>
<body>

<%= yield %>

</body>
</html>